var moduleDiv=document.getElementById('module');
var a=document.createElement('a');
a.setAttribute('href','/stylethree/Designations.jsp');
a.innerHTML='Designations';
moduleDiv.appendChild(a);
br=document.createElement('br');
moduleDiv.appendChild(br);
var b=document.createElement('b');
b.innerHTML='Employees';
moduleDiv.appendChild(b);
var br=document.createElement('br');
moduleDiv.appendChild(br);
a=document.createElement('a');
a.setAttribute('href','/stylethree/index.jsp');
a.innerHTML='Home';
moduleDiv.appendChild(a);